---
- name: Listen for events on a url
  hosts: localhost

  ## Define our source for events

  sources:
    - name: check web server
      ansible.eda.url_check:
        urls: 
          - "http://localhost:8080"
        delay: 10
        

  ## Define the conditions we are looking for

  rules:
    - name: check url status down
      condition: event.url_check.status == "down"
  ## Define the action we should take should the condition be met
      action:
        run_playbook:
          name: "./start-container.yml"
    
    - name: check url status up
      condition: event.url_check.status == "up"
      action:
        debug:
          msg: "Status up"